/**
 * Client-side uploader that uploads directly to ImageKit's official upload endpoint
 * using authentication signatures generated by /api/upload/signature.
 *
 * This completely bypasses Next.js server request body limits (HTTP 413 Payload Too Large),
 * allowing large files and high-definition videos (e.g. 50MB-100MB+) to upload reliably
 * with faster transfer speeds directly to the ImageKit CDN.
 */

export interface UploadResult {
  url: string;
  fileId?: string;
  name?: string;
  filePath?: string;
}

export async function uploadToImageKit(
  file: File,
  options?: {
    folder?: string;
  }
): Promise<UploadResult> {
  const isVideo = file.type.startsWith("video/");
  const defaultFolder = isVideo ? "/cartship/videos" : "/cartship";
  const folder = options?.folder || defaultFolder;

  // 1. Fetch authentication signature from backend
  const sigRes = await fetch("/api/upload/signature");
  if (!sigRes.ok) {
    const errData = await sigRes.json().catch(() => ({}));
    console.warn("Signature route error, attempting fallback upload:", errData);
    return uploadViaServer(file);
  }

  const { signature, expire, token, publicKey } = await sigRes.json();
  if (!signature || !publicKey) {
    return uploadViaServer(file);
  }

  const safeFileName = file.name
    ? file.name.replace(/[^a-zA-Z0-9.-]/g, "_")
    : `file_${Date.now()}`;

  const formData = new FormData();
  formData.append("file", file);
  formData.append("fileName", safeFileName);
  formData.append("publicKey", publicKey);
  formData.append("signature", signature);
  formData.append("expire", String(expire));
  formData.append("token", token);
  formData.append("folder", folder);
  formData.append("useUniqueFileName", "true");

  // Direct upload to ImageKit endpoint
  const res = await fetch("https://upload.imagekit.io/api/v1/files/upload", {
    method: "POST",
    body: formData,
  });

  if (!res.ok) {
    const errData = await res.json().catch(() => ({}));
    const errorMessage =
      errData.message || errData.help || `ImageKit upload failed with status ${res.status}`;
    throw new Error(errorMessage);
  }

  const data = await res.json();
  return {
    url: data.url,
    fileId: data.fileId,
    name: data.name,
    filePath: data.filePath,
  };
}

async function uploadViaServer(file: File): Promise<UploadResult> {
  const formData = new FormData();
  formData.append("file", file);

  const res = await fetch("/api/upload", {
    method: "POST",
    body: formData,
  });

  if (!res.ok) {
    const errData = await res.json().catch(() => ({}));
    throw new Error(errData.error || `Upload failed with status ${res.status}`);
  }

  return res.json();
}
